# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-27 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('birthYear', models.IntegerField(default=1900)),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('year', models.IntegerField(default=1900)),
                ('genre', models.CharField(choices=[('i', 'impressionism'), ('p', 'post-impressionism'), ('s', 'surrealism')], default='i', max_length=50)),
                ('author', models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibition.Artist')),
            ],
        ),
    ]
