# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-27 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='image',
            field=models.ImageField(default='https://avatars.mds.yandex.net/get-pdb/2979168/d8e27e17-e239-4175-9efb-3235a21eafea/s1200?webp=false', upload_to='/images'),
        ),
    ]
