# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-27 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_painting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Tizian_041.jpg/1024px-Tizian_041.jpg', max_length=1000),
        ),
    ]
